name: Registro de ponto

on:
  schedule:
    # 06:00 BRT -> 09:00 UTC, seg a sex
    - cron: "0 9 * * 1-5"
    # 10:00 BRT -> 13:00 UTC, seg a sex
    - cron: "0 13 * * 1-5"
    # 10:15 BRT -> 13:15 UTC, seg a sex
    - cron: "15 13 * * 1-5"
    # 12:15 BRT -> 15:15 UTC, seg a sex
    - cron: "15 15 * * 1-5"
  workflow_dispatch:  # permite rodar agora, manualmente

concurrency:
  group: ponto-schedule
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo
      SENIOR_USER: ${{ secrets.SENIOR_USER }}
      SENIOR_PASSWORD: ${{ secrets.SENIOR_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Sanity check secrets
        run: |
          [ -n "$SENIOR_USER" ] || { echo "::error::SENIOR_USER não definido"; exit 1; }
          [ -n "$SENIOR_PASSWORD" ] || { echo "::error::SENIOR_PASSWORD não definido"; exit 1; }

      - name: Run script
        run: python script.py

      # Opcional: se seu script gerar 'ponto.png' (screenshot), anexa como evidência
      - name: Upload evidências
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-ponto
          path: ponto.png
          if-no-files-found: ignore
